e-Card/Models/LaboratoryWorker.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace e_Card.Models
{
    [Table("LaboratoryWorker")]
    public class LaboratoryWorker : ApplicationUser
    {
        public int LaboratoryId { get; set; }

        [ForeignKey("LaboratoryId")]
        public Laboratory Laboratory { get; set; }

        public DateTime DateOfEmployment { get; set; }
    }
}

e-Card/Areas/AdministrationClinic/Controllers/LaboratoryWorkersController.cs
using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using e_Card.Areas.AdministrationClinic.Services;
using e_Card.Areas.AdministrationClinic.ViewModel;
using e_Card.Context.Implementation;
using e_Card.Controllers;
using e_Card.Helpers;
using e_Card.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace e_Card.Areas.AdministrationClinic.Controllers
{
    public class LaboratoryWorkersController : BaseController
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly LaboratoryWorkersService _laboratoryWorkersService = new LaboratoryWorkersService(new ApplicationDbContext());

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(new LaboratoryWorkerVm());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View("Create", new LaboratoryWorkerVm());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Update(string id)
        {
            var target = _db.Users.OfType<LaboratoryWorker>().FirstOrDefault(d => d.Id == id);

            if (target != null)
            {
                var labVm = new LaboratoryWorkerVm()
                {
                    LaboratoryWorkerId = target.Id,
                    Name = target.Name,
                    Surname = target.Surname,
                    Email = target.Email,
                    Gender = target.Gender,
                    MiddleName = target.MiddleName,
                    Birth = target.Birth,
                    Nationality = target.Nationality,
                    Address = target.Address,
                    LaboratoryId = target.LaboratoryId,
                    UrlImage = target.UrlImage,
                    DateOfEmployment = target.DateOfEmployment,
                };

                return View("Update", labVm);
            }
            return HttpNotFound();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_laboratoryWorkersService.Read().ToDataSourceResult(request));
        }

        [Authorize(Roles = "Admin")]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult LaboratoryWorkerHandler([DataSourceRequest] DataSourceRequest request, LaboratoryWorkerVm model, string status)
        {
            var success = false;
            if (model != null && ModelState.IsValid)
            {
                var accountController =
                    new AccountController { ControllerContext = ControllerContext };

                success = accountController.LaboratoryWorkerHandler(model, status);
            }

            return RedirectToAction(success ? "Index" : "Create");
        }

        [HttpPost]
        public JsonResult UploadImage(HttpPostedFileBase image)
        {
            if (image != null)
            {
                var extension = Path.GetExtension(image.FileName)?.ToLower();
                if (extension != ".jpg" && extension != ".png" && extension != ".jpeg")
                    return Json(new { success = false, error = "Wrong photo extension, please try with another photo." });

                Stream stream = image.InputStream;
                Image img = Image.FromStream(stream);
                var guid = Guid.NewGuid();

                var fileName = guid + extension;
                var physicalPath = Path.Combine(Server.MapPath("~/UserImages"), fileName);

                var myArray = (byte[])new ImageConverter().ConvertTo(img, typeof(byte[]));
                FileHelpers.SaveFile(myArray, physicalPath);

                return Json(new { success = true, path = "/UserImages/" + fileName, name = fileName });
            }

            return Json(new { success = false });
        }
    }
}

e-Card/Areas/AdministrationClinic/Views/LaboratoryWorkers/Create.cshtml
@using Kendo.Mvc.UI
@model e_Card.Areas.AdministrationClinic.ViewModel.LaboratoryWorkerVm

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("LaboratoryWorkerHandler", "LaboratoryWorkers", new { status = Consts.Create }))
{
    @Html.AntiForgeryToken()
    <div class="col-md-12 toppad">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Registruj korisnika</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4 col-lg-4">
                        <div class="form-group" id="userUrlImage" style="display: flex; justify-content: center;">
                            @*<img alt="User photo" src="" class="img-circle img-responsive userImageDimension">*@
                        </div>

                        <div class="col-md-12 col-xs-12">
                            @(Html.Kendo().Upload()
                                  .Name("image")
                                  .Async(a => a
                                      .Save("UploadImage", "LaboratoryWorkers")
                                      .AutoUpload(false)
                                  )
                                  .Events(e => e.Success("SuccessUpload"))
                                  .HtmlAttributes(new { style = "width:100%" })
                                  .Validation(validation => validation.AllowedExtensions(new[] { ".gif", ".jpg", ".png" }))
                                  .Multiple(false)
                                  )
                            @Html.ValidationMessageFor(m => m.UrlImage)
                        </div>
                    </div>


                    <div class="col-md-8 col-lg-8">
                        <table class="table table-user-information">
                            <tbody>
                            <tr>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Name">Ime</label>
                                        @Html.Kendo().TextBoxFor(m => m.Name).HtmlAttributes(new { style = "width:100%"})
                                        @Html.ValidationMessageFor(m => m.Name)
                                    </div>
                                </td>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Surname">Prezime</label>
                                        @Html.Kendo().TextBoxFor(m => m.Surname).HtmlAttributes(new {style = "width:100%"})
                                        @Html.ValidationMessageFor(m => m.Surname)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.DateOfEmployment">Datum zaposlenja</label>
                                        @(Html.Kendo().DatePicker()
                                              .Name("DateOfEmployment")
                                              .Value("")
                                              .HtmlAttributes(new {style = "width: 100%", title = "Invalid date"}))
                                        @Html.ValidationMessageFor(m => m.DateOfEmployment)
                                    </div>
                                </td>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Birth">Datum rođenja</label>
                                        @(Html.Kendo().DatePicker()
                                              .Name("Birth")
                                              .Value("")
                                              .Animation(true)
                                              .HtmlAttributes(new {style = "width: 100%", title = "Invalid date"}))
                                        @Html.ValidationMessageFor(m => m.Birth)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Gender">Spol</label>
                                        @(Html.Kendo().DropDownList()
                                              .Name("Gender")
                                              .Value("")
                                              .DataTextField("Text")
                                              .DataValueField("Value")
                                              .Text("Gender")
                                              .AutoBind(false)
                                              .BindTo(new List<SelectListItem>()
                                              {
                                                  new SelectListItem()
                                                  {
                                                      Text = Resource.Create_cshtml_Execute_Male,
                                                      Value = "Male"
                                                  },
                                                  new SelectListItem()
                                                  {
                                                      Text = "Female",
                                                      Value = "Female"
                                                  },
                                              })
                                              .HtmlAttributes(new {style = "width: 100%"}))
                                        @Html.ValidationMessageFor(m => m.Gender)
                                    </div>
                                </td>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.LaboratoryId">Labaratorija</label>
                                        @(Html.Kendo().ComboBoxFor(@m => m.LaboratoryId)
                                              .DataValueField("Id")
                                              .DataTextField("Name")
                                              .Value("")
                                              .Filter(FilterType.StartsWith)
                                              .DataSource(source =>
                                              {
                                                  source.Read(read =>
                                                  {
                                                      read.Action("GetLaboratories", "Laboratories", new {area = ""});
                                                  }).ServerFiltering(true);
                                              })
                                              .AutoBind(false)
                                              .HtmlAttributes(new {style = "width:100%;"})
                                              )
                                        @Html.ValidationMessageFor(m => m.LaboratoryId)
                                    </div>
                                </td>
                            </tr>

                            <tr>
                            <tr>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Nationality">Nacionalnost</label>
                                        @Html.Kendo().TextBoxFor(m => m.Nationality).HtmlAttributes(new {style = "width:100%"})
                                        @Html.ValidationMessageFor(m => m.Nationality)
                                    </div>
                                </td>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Address">Adresa stanovanja</label>
                                        @Html.Kendo().TextBoxFor(m => m.Address).HtmlAttributes(new {style = "width:100%"})
                                        @Html.ValidationMessageFor(m => m.Address)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                               
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Email">Email adresa</label>
                                        @Html.Kendo().TextBoxFor(m => m.Email).HtmlAttributes(new {type = "Email", style = "width:100%"})
                                        @Html.ValidationMessageFor(m => m.Email)
                                    </div>
                                </td>
                                <td>
                                    <div class="col-md-12 col-xs-12">
                                        <label for="@Model.Password">Lozinka</label>
                                        @Html.Kendo().TextBoxFor(m => m.Password).HtmlAttributes(new {type = "password", style = "width:100%"})
                                        @Html.ValidationMessageFor(m => m.Password)
                                    </div>
                                    @Html.HiddenFor(m => m.UrlImage)
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                @(Html.Kendo().Button()
                      .Name("primaryTextButton")
                      .HtmlAttributes(new { type = "submit", @class = "k-primary" })
                      .Content("Kreiraj korisnika"))
            </div>

        </div>
    </div>
}

<script id="errorTemplate" type="text/x-kendo-template">
    <div class="wrong-pass">
        <img src="@Url.Content("~/Images/errorIcon.png")" />
        <p>#= message #</p>
    </div>
</script>

<script>
    function SuccessUpload(data) {
        if (data.response.success) {
            document.getElementById('UrlImage').value = data.response.name;
            //$("#userUrlImage").css("background-image", 'url(/UserImages/' + data.response.name + ')');
            $("#userUrlImage").html("as");
        }
    }

    $(function() {
        $("form").kendoValidator();
    });
</script>

e-Card/Areas/AdministrationClinic/Views/LaboratoryWorkers/Index.cshtml
@using e_Card.Areas.AdministrationClinic.ViewModel
@using Kendo.Mvc.UI

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@(Html.Kendo().Grid<LaboratoryWorkerVm>()
      .Name("laboratoryWorker")
      .Columns(columns =>
      {
          columns.Bound(c => c.Name).Title(Resource.Title);
          columns.Bound(c => c.Surname).Title(Resource.Surname);
          columns.Bound(c => c.Gender).Title(Resource.Gender).Filterable(false);
          columns.Bound(c => c.Birth).Title(Resource.Birth).Filterable(false);
          columns.Bound(c => c.DateOfEmployment).Title("Datum zaposlenja");
          columns.Bound(c => c.Address).Title(Resource.Address).Filterable(false);
          columns.Template(@<text></text>).ClientTemplate("<a class='k-button k-button-icontext' href='" + Url.Action("Update", "LaboratoryWorkers", new { id = "#= LaboratoryWorkerId #" }) + "'><span class='k-icon  k-i-edit'></span>Update</a>");
          columns.Command(c => c.Destroy().Text("Izbriši"));
      })

      //.ToolBar(toolbar => toolbar.Create().Text("Dodaj bolest"))
      .ToolBar(t =>
      {
      t.Template(@<text>
                         <a class="k-button k-button-icontext" href="@Url.Action("Create", "LaboratoryWorkers")"><i class="fa fa-plus"></i>Dodaj laboranta</a>
                      </text>);
      })

      .Editable(editable => editable.TemplateName("_EditDoctor").Mode(GridEditMode.PopUp).Window(w => w.Width(430)))
      .Pageable()
      .Sortable()
      .Filterable()
      //.Events(e => e.Edit("onEdit"))
      .Scrollable(scrollable => scrollable.Height("auto"))
      .DataSource(dataSource => dataSource
          .Ajax()
          .PageSize(30)
          .Events(events => events.Error("error_handler"))
          .Model(model => model.Id(p => p.LaboratoryWorkerId))
          .Create(create => create.Action("LaboratoryWorkerHandler", "LaboratoryWorkers", new {status = Consts.Create}))
          .Read(read => read.Action("Read", "LaboratoryWorkers"))
          .Update(update => update.Action("LaboratoryWorkerHandler", "LaboratoryWorkers", new { status = Consts.Update }))
          .Destroy(update => update.Action("LaboratoryWorkerHandler", "LaboratoryWorkers", new { status = Consts.Delete }))
      ))

<script id="errorTemplate" type="text/x-kendo-template">
    <div class="wrong-pass">
        <img src="@Url.Content("~/Images/errorIcon.png")" />
        <p>#= message #</p>
    </div>
</script>

e-Card/Areas/AdministrationClinic/Views/LaboratoryWorkers/Update.cshtml
@using Kendo.Mvc.UI
@model e_Card.Areas.AdministrationClinic.ViewModel.LaboratoryWorkerVm

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("LaboratoryWorkerHandler", "LaboratoryWorkers", new { status = Consts.Update }))
{
    @Html.AntiForgeryToken()
    <div class="col-md-12 toppad">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Uredi korisnika</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4 col-lg-4">
                        <div class="form-group" id="userUrlImage" style="display: flex; justify-content: center;">
                            @*<img alt="User photo" src="" class="img-circle img-responsive userImageDimension">*@
                        </div>

                        <div class="col-md-12 col-xs-12">
                            <label for="@Model.UrlImage">Slika profila</label>
                            @(Html.Kendo().Upload()
                                  .Name("image")
                                  .Async(a => a
                                      .Save("UploadImage", "Doctors")
                                      .AutoUpload(false)
                                  )
                                  .Events(e => e.Success("SuccessUpload"))
                                  .Messages(m => m.Select("Dodaj sliku"))
                                  .Validation(validation => validation.AllowedExtensions(new[] { ".gif", ".jpg", ".png" }))
                                  .Multiple(false)
                            )
                        </div>
                    </div>


                    <div class="col-md-8 col-lg-8">
                        <table class="table table-user-information">
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.Name">Ime</label>
                                            @Html.Kendo().TextBoxFor(m => m.Name).Value(Model.Name).HtmlAttributes(new { style = "width:100%" })
                                            @Html.ValidationMessageFor(m => m.Name)
                                        </div>
                                    </td>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.Surname">Prezime</label>
                                            @Html.Kendo().TextBoxFor(m => m.Surname).Value(Model.Surname).HtmlAttributes(new { style = "width:100%" })
                                            @Html.ValidationMessageFor(m => m.Surname)
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.Gender">Spol</label>
                                            @(Html.Kendo().DropDownListFor(m => m.Gender)
                                              .Name("Gender")
                                              .DataTextField("Text")
                                              .DataValueField("Value")
                                              .Value(Model.Gender)
                                              .AutoBind(true)
                                              .BindTo(new List<SelectListItem>()
                                              {
                                                  new SelectListItem()
                                                  {
                                                      Text = "Male",
                                                      Value = "Male"
                                                  },
                                                  new SelectListItem()
                                                  {
                                                      Text = "Female",
                                                      Value = "Female"
                                                  },
                                              })
                                              .HtmlAttributes(new { style = "width: 100%", PlaceHolder = "Gender" })
                                            )
                                        </div>
                                    </td>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.LaboratoryId">Labaratorija</label>
                                            @(Html.Kendo().ComboBoxFor(@m => m.LaboratoryId)
                                              .DataValueField("Id")
                                              .DataTextField("Name")
                                              .Filter(FilterType.StartsWith)
                                              .Value(Model.LaboratoryId.ToString())
                                              .DataSource(source =>
                                              {
                                                  source.Read(read =>
                                                  {
                                                      read.Action("GetLaboratories", "Laboratories", new { area = "" });
                                                  }).ServerFiltering(true);
                                              })
                                              .AutoBind(true)
                                              .HtmlAttributes(new { style = "width:100%;" })
                                            )
                                        </div>
                                    </td>
                                </tr>

                                <tr>
                                <tr>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.Nationality">Nacionalnost</label>
                                            @Html.Kendo().TextBoxFor(m => m.Nationality).Value(Model.Nationality).HtmlAttributes(new { style = "width:100%" })
                                            @Html.ValidationMessageFor(m => m.Nationality)
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.Address">Adresa stanovanja</label>
                                            @Html.Kendo().TextBoxFor(m => m.Address).Value(Model.Address).HtmlAttributes(new { style = "width:100%" })
                                            @Html.ValidationMessageFor(m => m.Address)
                                        </div>
                                    </td>
                                    <td>
                                        <div class="col-md-12 col-xs-12">
                                            <label for="@Model.Email">Email adresa</label>
                                            @Html.Kendo().TextBoxFor(m => m.Email).Value(Model.Email).HtmlAttributes(new { type = "Email", style = "width:100%" })
                                            @Html.ValidationMessageFor(m => m.Email)
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    @Html.HiddenFor(m => m.UrlImage, new { value = Model.UrlImage })
                                    @Html.HiddenFor(m => m.LaboratoryWorkerId, new { value = Model.LaboratoryWorkerId })
                                    @Html.HiddenFor(m => m.DateOfEmployment, new { value = Model.DateOfEmployment })
                                    @Html.HiddenFor(m => m.Birth, new { value = Model.Birth })
                                </tr>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                @(Html.Kendo().Button()
                      .Name("primaryTextButton")
                      .HtmlAttributes(new { type = "submit", @class = "k-primary" })
                      .Content("Uredi korisnika"))
            </div>

        </div>
    </div>

}

<style>
    .buttonSubmit {
        position: relative;
        float: right;
    }
</style>

<script>
    function SuccessUpload(data) {
        if (data.response.success) {
            $("#userUrlImage").css("background-image", 'url(/UserImages/' + data.response.name + ')');
            //document.getElementById('UrlImage').value = data.response.name;
        }
    }

    $(document).ready(function () {
        $("#userUrlImage").css("background-image", 'url(/UserImages/@Model.UrlImage)');
    });
</script>

<script id="errorTemplate" type="text/x-kendo-template">
    <div class="wrong-pass">
        <img src="@Url.Content("~/Images/errorIcon.png")" />
        <p>#= message #</p>
    </div>
</script>